# Generated by Django 5.2.5 on 2025-08-28 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст вопроса (минимум 5 символов)', validators=[django.core.validators.MinLengthValidator(5, 'Вопрос должен содержать минимум 5 символов')], verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='qa_api_ques_created_72b35a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Уникальный идентификатор пользователя', verbose_name='Id пользователя')),
                ('text', models.TextField(help_text='Введите текст ответа (минимум 3 символа)', validators=[django.core.validators.MinLengthValidator(3, 'Ответ должен содержать минимум 3 символа')], verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('question', models.ForeignKey(help_text='Вопрос, к которому относится этот ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa_api.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['question', 'created_at'], name='qa_api_answ_questio_eceefa_idx'), models.Index(fields=['user_id'], name='qa_api_answ_user_id_fd6e10_idx')],
            },
        ),
    ]
